server:
  port: 8000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: health-analyzer-route
          uri: lb://ms-health-analyzer
          predicates:
            - Path=/api/v1/health-analyzer/**
          filters:
            - StripPrefix=2
        - id: patient-data-collector-route
          uri: lb://ms-patient-data-collector
          predicates:
            - Path=/vital-signs/**
          filters:
              - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway