spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  application:
    name: rabbitmq-vital-sign-processor

rabbitmq:
  queue:
    new-vital-sign: vital-sign-queue
  exchange:
    medical-events: medical-events-exchange
  routing-key:
    vital-sign: vital-sign-routing-key